services:
  api:
    build:
      context: .
    image: sogestsson/nostra-mysql-demo-api:latest
    container_name: nostra_mysql_demo_api
    ports:
      - "8000:8000"
    environment:
      MYSQL_HOST: ${MYSQL_HOST:-host.docker.internal}
      MYSQL_PORT: ${MYSQL_PORT:-4406}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-Superman}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-smart_stock}
    restart: unless-stopped
